In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/wasiqaliyasir/digital-mnist-dataset/mnist.csv

In [2]:
df = pd.read_csv('/kaggle/input/datasets/wasiqaliyasir/digital-mnist-dataset/mnist.csv')

In [3]:
df.head()

,label,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
0,7,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,2,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [4]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=2)

In [5]:
X_train

,1x1,1x2,1x3,1x4,1x5,1x6,1x7,1x8,1x9,1x10,...,28x19,28x20,28x21,28x22,28x23,28x24,28x25,28x26,28x27,28x28
8856,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1545,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
8136,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7768,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7782,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1099,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2514,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6637,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2575,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
7336,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [7]:
lor = LogisticRegression()
dt = DecisionTreeClassifier()

In [8]:
lor.fit(X_train, y_train)
dt.fit(X_train, y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [9]:
y_pred1 = lor.predict(X_test)
y_pred2 = dt.predict(X_test)

In [10]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [11]:
precision_score(y_test, y_pred1, average='macro')

0.8835134197338176

In [12]:
recall_score(y_test, y_pred2, average='macro')

0.8036078045686825

In [13]:
f1_score(y_test, y_pred2, average='macro')

0.8032026719352556

In [14]:
from sklearn.metrics import classification_report
print(classification_report(y_test, y_pred1))

              precision    recall  f1-score   support

           0       0.95      0.96      0.96       215
           1       0.98      0.97      0.97       239
           2       0.84      0.87      0.86       209
           3       0.83      0.90      0.86       186
           4       0.91      0.88      0.89       189
           5       0.78      0.76      0.77       162
           6       0.93      0.92      0.93       196
           7       0.93      0.90      0.91       225
           8       0.82      0.80      0.81       194
           9       0.86      0.88      0.87       185

    accuracy                           0.89      2000
   macro avg       0.88      0.88      0.88      2000
weighted avg       0.89      0.89      0.89      2000